### ISSUE TITLE
Adding another test folder in VisualPHPUnit 3.x

### ISSUE THREAD

**Issue by bobc82** [VisualPHPUnit/VisualPHPUnit#163] opened 2016-08-31 12:35 UTC
Hi,

i tried to add another test folder in vpu.json file as follows:

```
{
    "config":{
        "test-directories":[
            {
                "name":"VisualPHPUnit tests",
                "path":"../tests",
                "ignoreHidden":true
            },
            **{
                "name":"Custom tests",
                "path":"/opt/lampp/htdocs/custom/application/tests",
                "ignoreHidden":true
            }**
        ],
        "database":{
            "driver":"pdo_sqlite"
        }
    }
}
```
But when i open the home page on localhost:8000 via browser i don't see any folder... Any help would be appreciated!

**Comment by HeinDR** [comment] 2016-08-31 21:05
I had the same problem. However I'm not able to reproduce it. So maybe this is fixed by running the ```grunt --force``` command. (see my last comment on your former issue). Before I've solved it by changing the regex in the ```explodeTestName``` in ```src/Core/Parser``` from:   
```preg_match('/([a-zA-Z0-9]+)::([a-zA-Z0-9_]+)$/', $testName, $matches);```
 to:
```preg_match('/([a-zA-Z0-9]+)::([a-zA-Z0-9_]+)/', $testName, $matches);```

Hope this solves your problem.

**Comment by bobc82** [comment] 2016-09-01 08:12
Unfortunately this doesn't resolve the problem...
I run the command grunt --force (obviously renaming back the docroot in Run.php from app to dist) and it worked fine, but when i try another test folder i don't see any folder even after i changed the regexp in explodeTestName!

**Comment by HeinDR** [comment] 2016-09-01 09:33
Do you extend your test classes on ```PHPUnit_Framework_TestCase```? In ```src/API/Action/Test.php``` the ```isPhpUnitTestCase``` method looks for this class. I our case we extended on ```TestCase``` so I replaced that in that method to see al my tests.

**Comment by bobc82** [comment] 2016-09-02 09:18
If i well understood i made this replacement in this method into src/Api/Action/Test.php:
```
private function isPhpUnitTestCase($path)
    {
        //$result1 = preg_grep('/PHPUnit_Framework_TestCase$/', file($path)); /*changed to TestCase in new line*/
        $result1 = preg_grep('/TestCase$/', file($path));
        return !empty($result1);
    }
```
In fact my test classes extend TestCase class, but i continue to don't see anything...

**Comment by localgod** [comment] 2016-09-08 15:12
Hi @bobc82 and @HeinDR 
I have updated the build instructions to better describe the setup. Please see if this helps.
Compared to VPU version 2.x, that parsed the json output from phpunit, VPU version 3.x runs the actual test(s) by using the phpunit api.
This has benefits and drawbacks. One drawback is that you need to take additional steps if your tests extends  `PHPUnit_Framework_TestCase` and it cause VPU to fail if the phpunit version used by VPU is substantial different from the one the test is written in. Your bootstrap file also need load your extended test class.

If you look at [this section](https://github.com/VisualPHPUnit/VisualPHPUnit/blob/master/src/Api/Action/Test.php#L155) you can see how you can extend support for other testcases. 
then you just need to add a `bootstrap.php` in your test folder for autoloading and you should be good to go.

In the future in might make sense to move the `isPhpUnitTestCase` matching pattern to the config file.

Hope this helps.

**Comment by localgod** [comment] 2016-10-24 13:58
As there has been no comments on this issue for a long time I'm closing it and moved the matching  suggestion to issue #171.

**Closed by localgod** 2016-10-24 13:58 UTC
Labels: 3.x, Improvement
